In [59]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [61]:
card_data=pd.read_csv('creditcard.csv.csv')

In [62]:
card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [63]:
card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [64]:
card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [69]:
card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
card_data['V25']=card_data['V25'].fillna(card_data['V19'].mean())
card_data['V26']=card_data['V26'].fillna(card_data['V26'].mean())
card_data['V26']=card_data['V26'].fillna(card_data['V26'].mean())
card_data['V27']=card_data['V27'].fillna(card_data['V27'].mean())
card_data['V28']=card_data['V28'].fillna(card_data['V28'].mean())
card_data['Amount']=card_data['Amount'].fillna(card_data['Amount'].mean())
card_data['Class']=card_data['Class'].fillna(card_data['Class'].mean())

In [71]:
card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [73]:
card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [75]:
 legit=card_data[card_data.Class==0]
 fraud=card_data[card_data.Class==1]

In [77]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [79]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [81]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [83]:
 card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [85]:
legit_sample=legit.sample(n=492)

In [87]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [89]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1472,1151.0,1.450342,-1.091553,0.417343,-1.478394,-1.241929,-0.147628,-1.083722,-0.061393,-1.802212,...,-0.236717,-0.290964,0.035104,-0.444398,0.257503,-0.225392,0.056768,0.023932,38.00,0
212609,138926.0,-1.041045,1.680828,-1.606615,0.085209,0.717469,-1.518850,0.216219,0.656474,-0.798274,...,0.393124,0.931131,-0.285609,-0.184755,-0.537943,-0.189297,-0.076738,0.061877,1.00,0
162340,115032.0,1.856102,-0.197595,-1.760694,0.520476,-0.051813,-1.264694,0.168678,-0.184765,0.557643,...,0.282270,0.699226,-0.070864,-0.025973,0.128093,-0.129661,-0.031215,-0.030208,81.38,0
65149,51450.0,-1.273662,-0.598779,1.120470,-2.624574,-0.497352,-0.410592,-0.913430,0.568467,-2.203288,...,-0.367097,-1.090448,-0.188403,-1.100337,0.386995,-0.390860,0.175279,-0.041354,25.90,0
77866,57253.0,-1.326962,2.453009,1.881737,4.491310,-0.347467,1.410886,-1.120662,-1.987965,-2.333450,...,-1.564751,-0.313056,0.142072,0.004633,-0.045490,0.128168,0.217834,0.138835,7.00,0

In [91]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [93]:
X=new_dataset.drop(columns='Class', axis=1)
Y=new_dataset['Class']

In [95]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
1472      1151.0  1.450342 -1.091553  0.417343 -1.478394 -1.241929 -0.147628
212609  138926.0 -1.041045  1.680828 -1.606615  0.085209  0.717469 -1.518850
162340  115032.0  1.856102 -0.197595 -1.760694  0.520476 -0.051813 -1.264694
65149    51450.0 -1.273662 -0.598779  1.120470 -2.624574 -0.497352 -0.410592
77866    57253.0 -1.326962  2.453009  1.881737  4.491310 -0.347467  1.410886
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
1472   -1.083722 -0.061393 -1.802212  ... -0.249190 -0.236717 -0.290964
212609  0.216219  0.656474 -0.798274  ... -0.303755  0.393124  0.931131
162340  0.168678 -0.184765  0.557643  ... -0.142055  0.282270  0.699226
65149  -0.913430  0.568467 -2.203288  ... -0.093562 -0.367097 -1.090448
77866  -1.120662 -1.987965 -2.333450  ...  0.975480 -1.564751 -0.313056
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
1472    0.035104 -0.444398  0.257503 -0.225392  0.056768  0.023932   38.00
212609 -0.285609 -0.184755 -0.537943 -0.189297 -0.076738  0.061877    1.00
162340 -0.070864 -0.025973  0.128093 -0.129661 -0.031215 -0.030208   81.38
65149  -0.188403 -1.100337  0.386995 -0.390860  0.175279 -0.041354   25.90
77866   0.142072  0.004633 -0.045490  0.128168  0.217834  0.138835    7.00
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [97]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20,stratify=Y, random_state=2)

In [99]:
print(X_train, X_test, Y_train, Y_test)

            Time         V1        V2         V3        V4         V5  \
100623   67571.0  -0.758469 -0.045410  -0.168438 -1.313275  -1.901763
45073    42198.0  -0.137293  0.921873   1.899380  0.969058   0.186116
156707  108747.0   1.996255 -0.082643  -0.154774  0.514144  -0.491905
232243  147096.0  -3.510109 -0.108008   0.190817 -1.031012  -0.261038
260155  159427.0   2.069327  0.312982  -1.732422  0.487300   0.351427
...          ...        ...       ...        ...       ...        ...
278968  168559.0   1.991711  0.120814  -1.732085  0.551007   0.168031
71283    54239.0  -3.071650  2.518234   0.595541 -1.913822  -0.733299
223618  143456.0  -2.006582  3.676577  -5.463811  7.232058  -1.627859
43061    41353.0 -15.020981  8.075240 -16.298091  5.664820 -11.918153
149345   91055.0   2.079134  0.171764  -1.855045  0.645674   0.507200

              V6         V7        V8        V9  ...       V20       V21  \
100623  0.739433   3.071892 -0.483422  0.618203  ... -0.032500  0.042619
45073   0.041187   0.713262 -0.191404 -0.510887  ...  0.178620 -0.062197
156707 -0.649900  -0.486927 -0.208403  2.473660  ... -0.232745 -0.256635
232243  1.904043   0.619215  0.703787 -0.682196  ... -1.028529 -0.559762
260155 -1.408832   0.365443 -0.465943  0.390512  ... -0.113200  0.201689
...          ...        ...       ...       ...  ...       ...       ...
278968 -1.427989   0.306979 -0.384846  0.568316  ... -0.145372  0.220628
71283  -0.579462   0.177639  0.570967  1.639776  ...  1.123744 -0.329760
223618 -0.996755  -4.299833  2.268867 -3.651067  ...  0.474414  0.713907
43061  -4.246957 -14.716668  9.435084 -6.795398  ... -0.995787  2.525115
149345 -1.445819   0.652380 -0.597481  1.712704  ... -0.320047 -0.014072

             V22       V23       V24       V25       V26       V27       V28  \
100623  0.397224  0.072229 -0.242276  0.560916 -0.540955  0.150606 -0.117140
45073   0.085689  0.064135  0.074754 -0.770524 -0.590637  0.066157 -0.038987
156707 -0.301052  0.351520 -0.178828 -0.365159 -0.958423  0.041596 -0.032429
232243 -0.133591  0.045993 -1.699753  0.803753 -0.569479 -0.468522 -0.002294
260155  0.828489 -0.055085 -0.135993  0.320188 -0.098940  0.006611 -0.029678
...          ...       ...       ...       ...       ...       ...       ...
278968  0.759236 -0.041025 -0.072207  0.231407 -0.101862 -0.003968 -0.026303
71283  -0.127086  0.085060  0.196269 -0.067770  0.681342  0.463583 -0.086344
223618 -0.063868  0.167947 -0.449864  0.023702  0.536905  0.485864 -0.042393
43061  -0.832074 -0.186117  0.429781  0.697103  0.056031 -1.310888 -0.707403
149345  0.410951 -0.073677 -0.103230  0.515120 -0.099641 -0.080914 -0.080753

        Amount
100623  549.06
45073    19.99
156707    2.12
232243  172.00
260155    3.13
...        ...
278968   32.85
71283     0.45
223618    1.00
43061    34.12
149345   15.77

[787 rows x 30 columns]             Time         V1         V2         V3         V4         V5  \
247995  153761.0   1.146259   1.403458  -4.159148   2.660107  -0.323217
49095    43909.0   1.137634  -0.884178   0.668989  -0.707366  -1.211077
277390  167624.0   2.025858  -0.007107  -1.098014   0.435970  -0.027425
52870    45691.0  -0.288839   0.879783   1.604548  -0.239439   0.349409
15451    26833.0 -20.532751  12.373989 -23.009003   6.144821 -15.587296
...          ...        ...        ...        ...        ...        ...
108258   70828.0   0.196707   1.189757   0.704882   2.891388   0.045555
12108    21046.0 -16.917468   9.669900 -23.736443  11.824990  -9.830548
99506    67150.0  -1.824295   0.403327  -1.994122   2.756558  -3.139064
74496    55614.0  -7.347955   2.397041  -7.572356   5.177819  -2.854838
153498   99230.0   1.991786   0.358539  -1.448114   1.601132   0.580691

              V6         V7         V8        V9  ...       V20       V21  \
247995 -1.836071  -1.623740   0.259562 -1.132044  ...  0.284831  0.564450
49095  -0.271131  -0.777509   0.127328 -0.879432  ...  0.176221  0.126599
277390 -1.126731   0.269690  -0.344766  0.664664  ... -0.210567 -0.240144
52870  -1.299227   1.003293  -0.417303 -0.431175  ...  0.028904 -0.213934
15451  -4.384491 -15.939003  13.696416 -3.948455  ...  1.592754  1.754608
...          ...        ...        ...       ...  ...       ...       ...
108258  1.245730  -1.198714  -2.421616 -1.232089  ...  0.646616 -1.328132
12108  -2.514829 -17.290657   1.820408 -6.264903  ...  0.996745 -2.336111
99506   0.408185  -1.209045   1.095634 -1.447225  ...  1.503688  0.838760
74496  -1.795239  -8.783235   0.437157 -3.740598  ...  0.073164 -0.175273
153498 -1.068351   0.656222  -0.569849  1.313326  ... -0.229784 -0.074791

             V22       V23       V24       V25       V26       V27       V28  \
247995  0.445744 -0.141136 -0.265517  0.362260 -0.416062  0.507370  0.243744
49095   0.034431  0.077598  0.208959  0.061787 -0.418739  0.010930  0.026038
277390 -0.510796  0.288210 -0.031786 -0.114408 -0.583183 -0.004859 -0.047597
52870  -0.498851  0.009924  0.683465 -0.324784 -0.133344 -0.155189 -0.164418
15451  -1.466115 -0.856779  0.125777  1.402587 -0.223755  1.574249  0.469201
...          ...       ...       ...       ...       ...       ...       ...
108258  0.189311 -0.005524 -0.814708  0.400924  0.286281  0.135215  0.257315
12108   0.972755  1.241866 -1.051086  0.038009  0.672317  2.108471 -1.421243
99506   0.341727  0.947506 -0.145493  0.049326  0.831065  0.332421  0.252713
74496   0.543325 -0.547955 -0.503722 -0.310933 -0.163986  1.197895  0.378187
153498  0.269374 -0.022208 -0.036701  0.465394 -0.534105 -0.037996 -0.062336

        Amount
247995   51.37
49095    92.00
277390    9.99
52870     1.29
15451    99.99
...        ...
108258    0.76
12108     1.00
99506   489.71
74496     0.83
153498   29.70

[197 rows x 30 columns] 100623    1
45073     0
156707    0
232243    0
260155    0
         ..
278968    0
71283     0
223618    1
43061     1
149345    0
Name: Class, Length: 787, dtype: int64 247995    1
49095     0
277390    0
52870     0
15451     1
         ..
108258    1
12108     1
99506     1
74496     1
153498    0
Name: Class, Length: 197, dtype: int64

In [101]:
model = LogisticRegression()
model.fit(X_train, Y_train)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [103]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [105]:
print('training_data_accuracy',training_data_accuracy)

training_data_accuracy 0.9504447268106735

In [107]:
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [109]:
print('Accuracy score on test data:',test_data_accuracy)

Accuracy score on test data: 0.9238578680203046